winrm.go, winrm/client.go
Fixes masterzen/winrm#17
When the command exits, the ExitCode is returned. In the case of an error, 0 is the exit code returned, as the user should be checking the error.
=> Return the ExitCode() from the command

winrm.go, winrm/client.go, winrm/client_test.go, winrm/command_test.go, winrm/endpoint.go, winrm/endpoint_test.go, winrm/http.go, winrm/http_test.go, winrm/powershell.go, winrm/shell_test.go
=> Support for passing in a CA Certificate, skipping SSL validation, and

winrm/client.go, winrm/command.go
This builds on #24 by fixing an issue where `winrm` would error if the command being run didn't output any data to standard output or standard error for over 60 seconds.
=> Fix an issue where no output for 60 seconds would throw an error

winrm/client.go, winrm/command.go
Currently if an error occurs during command execution (such as a non-200 status code from WinRM server or a network interruption), WinRM will exit with an error code of 0 and not indicate that an error has occurred.
This ensures the error is passed through from `slurpAllOutput` to the return code of the program.
This is also how I discovered that with a Windows 8.1 remote host, I was getting the following error (due to the command not outputting data to stdout / stderr frequently enough):
```
http error: 500 - <s:Envelope xml:lang="en-US" xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:x="http://schemas.xmlsoap.org/ws/2004/09/transfer" xmlns:e="http://schemas.xmlsoap.org/ws/2004/08/eventing" …
```
=> Ensure error is returned if network or HTTP error occurs during command execution

Makefile
As the title says, in some cases (cygwin and MinGW) make was not output the colors properly. I believe this is the case no linux as well, this should take care of it.
=> Fix Makefile so it properly outputs ANSI colors

winrm/command_test.go, winrm/parameters.go, winrm/request.go
With these changes running ```go test -race -v ./...``` results in a clean run of the tests.
=> Fix race conditions

README.md, winrm/client.go, winrm/client_test.go, winrm/parameters.go
Allows addition of logic to (or complete replacement of) the http stack
=> Add TransportDecorator to the parameter set

winrm/http_test.go
Windows boxes may have WSMAN running and thus the default port is not available for testing. Changing that port.
=> Make tests run on Windows boxes

development/sample_requests.txt, winrm/request.go
I'm playing with Windows Nano Servers and it seems that Nano only supports codepage UTF-8.
After changing the codepage from 437 to 65001 I can use this command to communicate with such a Nano Server.
Equivalent change for Ruby https://github.com/WinRb/WinRM/pull/130
More details about Nano Server and having a packer template can be found in this blog post: http://www.hurryupandwait.io/blog/a-packer-template-for-windows-nano-server-weighing-300mb
=> Set default codepage UTF-8

README.md
Azure has moved Paul's code from his personal repository to the Azure repository.  I'm updating the README to change the pointer.
=> Point to official go-ntlmssp repo.

README.md, winrm/endpoint.go
The readme doc needs to be updated, also created a more idiomatic go way to alloc a new strut making a simple function.
=> doc fix + idiomatic way for new endpoint struct

winrm.go, winrm/client.go, winrm/command_test.go, winrm/endpoint.go, winrm/endpoint_test.go
When the windows firewall is on, and winrm is not blocked, the connection
will be accepted but no response will be sent by the winrm server.
In this case, the winrm client will wait almost indefinitely.
This prevents packer from being able to detect when winrm is ready on
a prepared VM.
The default timeout is 60s (which should be enough for running a command
on a winrm enabled host), but still not too much so that Packer doesn't
wait too long.
The timeout is overridable (check -timeout for the winrm command, or through
the Endpoint mechanism with NewEndpointWithTimeout).
Of course this requires changes in Packer if one wants to be able to modify the timeout.
Do any of @dylanmei , @pecigonzalo, @mefellows , @boumenot (or anyone else) wants to take care of adding the timeout on the Packer …
=> Fix #46 add a connect+wait header time out

winrm/client.go, winrm/client_test.go, winrm/command.go, winrm/command_test.go, winrm/fixture_test.go, winrm/http.go
Since PR #25 winrm is now unfortunately reporting up `OperationTimeout` errors when the command doesn't output anything, and aborting processing.
This changeset is PR #26 by @pecigonzalo which I rebased in order to be able to merge it on top of current master.
=> Fix #48 - OperationTimeout aborts the current command

Makefile, soap/header_test.go, soap/message_test.go, soap/namespaces_test.go, winrm/client_test.go, winrm/fixture_test.go, winrm/http_test.go
This improves globally the test coverage, especially:
* soap headers and messages building
* end-to-end client function `Run`, `RunWithString` and `RunWithInput`
=> Increase test coverage

auth.go
Azure removed their fork of http/tls because this is now part of Go 1.7
Since we still want to be compatible with Go 1.6, we're now depending
of a fork of Azure/azure-sdk-for-go that still contain the http/tls fork.
This will be removed once we'll support Go1.7
=> (#60) Use my own fork of azure-sdk-for-go

README.md, ntlm.go, ntlm_test.go
Currently the Azure builder in mitchellh/packer is based on winrm. Unfortunately the change from
`TransportDecorator func(*http.Transport) http.RoundTripper`
to 
`TransportDecorator func() Transporter`
broke packers Azure builder implementation that uses NTLM. Since the basic HTTP implementation (`type clientRequest struct{...}`) is private to winrm I propose to move it here.
=> proposal to add support for NTLMv2 via Microsofts go-ntlmssp

http.go
This will make winrm work with proxies out of the box.
There was an issue requesting this at mitchellh/packer#4418
While we could make our own transport, there's so much config logic in `clientRequest.Transport` that I think it makes more sense to modify it upstream. Otherwise I'd worry about getting out of sync.
=> default transport: proxy from environment

auth.go, http.go
Needed to fix an issue reported at https://github.com/hashicorp/packer/issues/4848 where connections with long periods of inactivity would be dropped. This patch has been tested by a user on that thread and shown to work
=> Set KeepAlive and dial timeout to defaults

auth.go
just noticed this change was made to the http transport, but not to the auth transport
=> also add ProxyFromEnvironment to auth transport.

.gitignore, command_test.go, fixture_test.go, ntlm.go, request.go, request_test.go, response.go, response_test.go, shell.go, soap/header.go, soap/header_test.go, soap/message.go, soap/message_test.go, soap/namespaces.go, soap/namespaces_test.go
Replaces the LGPL dependency `masterzen/xmlpath` with `ChrisTrenkamp/goxpath`,
which is under the `MIT` license.
Underlying API's should be the same, and there aren't any expected
breaking changes to any public functions exposed via this WinRM library.
This change is solely to modify dependencies away from an LGPL license.
```
$ make test
==> Installing dependencies
==> Testing...
go test ./...
ok      github.com/grubernaut/winrm     5.050s
ok      github.com/grubernaut/winrm/soap        0.003s
```
=> Remove LGPL dependencies

.travis.yml, client.go
This doesn't happen with Go < 1.10, but there was a race condition in
`RunWithString` and `RunWithInput` which had already been fixed in `Run`.
It was possible for the function to return while the `stdout` or `stderr`
copy was still in progress. Since `bytes.Buffer` is not thread safe, the
`outwriter.String()` could see an intermediate buffer state while it
was growing, leading to strange results.
=> Fix #77 - fix RunWithString race condition

README.md, auth.go, client.go, client_test.go, http.go, http_test.go, ntlm.go, ntlm_test.go, parameters.go
This allows to e.g. easily tunnel WinRM connection via SSH to connect
to hosts in a private subnet with access only through a jump host.
The context of this change is to allow tunneling WinRM via SSH bastion host in terraform provisioners
The PR introduces a breaking change to the API so if you see a better way to introduce support for custom dialers, I'm more than happy to change the code.
=> Add support for custom dialers.

go.mod, go.sum, request.go
The current Go uuid module is not maintained and is buggy. Note that
the new maintained one may panic if crypto/rand fails but this is not
likely under any normal circumstance.
Signed-off-by: Justin Cormack <justin.cormack@docker.com>
=> Switch to maintained uuid module

README.md, auth.go, go.mod
This PR adds TLS renegotiation. Without it, when using client x509 certificates, you get an error like:
```bash
gabriel@rossak:/tmp/ssc$ go run client.go
2020/05/18 16:11:04 failed to run command: "unknown error Post \"https://192.168.122.142:5986/wsman\": local error: tls: no renegotiation"
```
With renegotiation enabled:
```bash
gabriel@rossak:/tmp/ssc$ go run client.go 
win-dceir3c7qnq\administrator
```
=> Add renegotiation

client.go, command.go, fixture_test.go, request.go, request_test.go
Fixes #104
Closes #82 
Sets `@End = true` in the input stream when closing Stdin or sending a single string instead of a stream.
=> Send Stdin EOF on Close()

auth.go, command_test.go, http.go, ntlm.go, request.go, response.go, response_test.go, shell_test.go
I've fixed couple of linter warnings.
In https://github.com/masterzen/winrm/blob/c42b5136ff886aff9dba40fb3670281f0d583db8/http.go#L124 line, returned struct should be public (starts with uppercase) to be able to access it's contents. That struct is being used in many places so I haven't touched it.
=> Go Linter Fixes.

ntlm.go
Creates NewClientNTLMWithProxyFunc function. 
Similar to NewClientWithProxyFunc and NewClientNTLMWithDial, except for NTLM. https://github.com/hashicorp/packer/issues/10343 highlights packer loses NTLM settings if proxyfunc exists, therefore adding this would help resolve this issue in the Packer repository.
=> Add Client NTLM With Proxy Func

auth.go, client.go, go.mod, http.go
1. Wrapping the errors returned by winrm, which can help the client package to take better decisions by unwrapping the error.
2. Ran go mod tidy.
=> Wrapped errors

.golangci.yml, README.md, auth.go, client.go, client_test.go, command.go, command_test.go, error.go, error_test.go, fixture_test.go, http.go, http_test.go, kerberos.go, ntlm.go, ntlm_test.go, response.go, response_test.go, shell.go, shell_test.go, soap/header.go, soap/namespaces.go
This solves the issue https://github.com/masterzen/winrm/issues/125.
=> Support canceling remote commands via context. (#1)

soap/namespaces.go
The list contained the same strings that were defined as constants right above the list.
=> Dry up DOM namespaces list

command.go
Fixes #147 
In addition to the existing SOAP OperationTimeout, this PR makes the output retriever check if the error returned from the HTTP request is a http/timeout, which needs to be handled the same way.
=> Fix http/timeout while waiting for command output

encryption.go
HTTP response's body should always be read and closed even if it's not used. The `PrepareRequest` function in encryption.go did not do that. This prevents the http client from reusing the same TCP connection to send the next request and a new one is opened, leaving the old one hanging.
=> Read and close PrepareRequest response body

encryption.go
Some error messages were claiming that "protocol is not supported on pywinrm".
=> Reword "not supported in pywinrm" errors

.github/workflows/lint.yaml, .golangci.yml
There's a `.golangci.yml` but no workflow. There are a some linting errors and warnings, so maybe need to fix those first. Most of them seem to be in the encryption.go.
=> Add a golangci-lint workflow
